config/routes.rb
Rails.application.routes.draw do
  # devise_for :users
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root 'fas#index'

  # Resourceful routes for fas
  resources :fas do
    collection do
      get 'graphs'
      get 'export_excel'
      delete 'destroy_old'
      post 'submit_barcode_data'
      post 'update_status_and_remarks'
      match 'search', via: [:get, :post]
      get 'export_to_excel', as: 'export_to_excel'
    end
    member do
      get 'barcodes'  # New route for displaying barcode data
      get 'submitted_data'
    end
  end
  resources :barcodes
  # This route will catch any undefined route and render the error page
  match "*path", to: "application#render_error", via: :all
end

app/views/shared/_sidebar.html.erb
<nav class="navbar bg-primary" data-bs-theme="dark">
  <div class="container-fluid">
    <%= link_to new_fa_path, class: "navbar-brand", style: "color: white; font-weight: bold;" do %>
      <img src="/house-solid.svg" style="height: 20px;width: 30px;">
      Home
    <% end %>
    <div class="current-info ms-auto" style="color: white;">
      <%#= Time.now.strftime("%A") %> <%#= Time.now.strftime("%H:%M") %>
       <marquee><%= Barcode.all.where(status: nil).count %> Batteries are Pending for analysis</marquee>
    </div>
    <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasDarkNavbar" aria-controls="offcanvasDarkNavbar" aria-label="Toggle navigation" data-bs-toggle="tooltip" data-bs-placement="down" title="Menu Page">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="offcanvas offcanvas-start text-bg-white" style="background-color: #0D6EDD;" tabindex="-1" id="offcanvasDarkNavbar" aria-labelledby="offcanvasDarkNavbarLabel">
      <div class="offcanvas-header">
        <h4 class="offcanvas-title" id="offcanvasDarkNavbarLabel" style="color: white;">Content</h4>
        <button type="button" class="btn-close btn-close-white" data-bs-dismiss="offcanvas" aria-label="Close"></button>
      </div>
      <div class="offcanvas-body">
        <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
          <li class="nav-item">
            <%= link_to new_fa_path, class: 'nav-link active', aria: { current: 'page' }, style: "color: white;" do %>
              <img src="/house-solid.svg" style="height: 20px;width: 30px;">
              Home
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to root_path, class: 'nav-link active', style: "color: white;" do %>
              <img src="/list-solid.svg" alt="FA List" style="height: 20px;width: 30px;">
              FA Data List
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to submitted_data_fa_path(2), class: 'nav-link active', style: "color: white;" do %>
              <img src="/database-solid.svg" alt="FA List" style="height: 20px;width: 30px;">
              Failure Analysis Data
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to search_fas_path, class: 'nav-link active', style: "color: white;", id: 'openPasswordModal', data: { bs_toggle: 'offcanvas', target: '#offcanvasPassword' } do %>
              <img src="/search.svg" alt="FA List" style="height: 20px;width: 30px;">
              Search Barcode
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to graphs_fas_path, class: 'nav-link active', style: "color: white;" do %>
              <img src="/chart.svg" alt="FA List" style="height: 20px;width: 30px;">
              FA Dashboard
            <% end %>
          </li>
        </ul>
      </div>
    </div>
  </div>
</nav>

<div class="offcanvas offcanvas-start text-bg-white" style="background-color: #0D6EDD;" tabindex="-1" id="offcanvasPassword" aria-labelledby="offcanvasPasswordLabel">
  <div class="offcanvas-header">
    <h4 class="offcanvas-title" id="offcanvasPasswordLabel" style="color: white;">Enter Password</h4>
    <button type="button" class="btn-close btn-close-white" data-bs-dismiss="offcanvas" aria-label="Close"></button>
  </div>
  <div class="offcanvas-body">
    <%= form_with url: search_fas_path, method: :post do %>
      <div class="mb-3">
        <%= label_tag :password, 'Password:', class: 'form-label', style: 'color: white;' %>
        <%= password_field_tag :password, nil, class: 'form-control', style: 'color: black;' %>
      </div>
      <%= submit_tag 'Submit', class: 'btn btn-primary', style: 'color: white; background-color: mediumblue;' %>
    <% end %>
  </div>
</div>

<script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>

<script>
  $(document).ready(function() {
    $('#openPasswordModal').on('click', function() {
      $('#offcanvasPassword').offcanvas('show');
    });
  });
</script>

app/views/shared/error.html.erb
<!-- app/views/shared/error.html.erb -->

<!DOCTYPE html>
<html>
<head>
  <title>Error</title>
  <!-- Add your stylesheets and other head elements as needed -->
</head>
<body>

  <div class="error-container">
    <h1>Error</h1>
    <p><%= @error_message %></p>
    <%= link_to 'Home', root_path, class: 'btn btn-primary' %>
  </div>

</body>
</html>