config/routes.rb
Rails.application.routes.draw do
  # devise_for :users
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root 'fas#index'

  # Resourceful routes for fas
  resources :fas do
    collection do
      get 'graphs'
      get 'export_excel'
      delete 'destroy_old'
      post 'submit_barcode_data'
      post 'update_status_and_remarks'
      match 'search', via: [:get, :post]
      get 'export_to_excel', as: 'export_to_excel'
    end
    member do
      get 'barcodes'  # New route for displaying barcode data
      get 'submitted_data'
    end
  end
  resources :barcodes
  # This route will catch any undefined route and render the error page
  match "*path", to: "application#render_error", via: :all
end

app/models/fa.rb
class Fa < ApplicationRecord
  # other attributes in your model
  has_many :barcodes, dependent: :destroy

  before_create :set_default_date_and_time

  validates :Line, presence: true
  validates :Model, presence: true
  validates :qty, presence: true, numericality: { only_integer: true }
  validate :validate_qty_limit

  scope :older_than_two_months, -> { where("created_at < ?", 2.months.ago) }

  LINES = ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10',
   '11', '12', '13', '15', '16', '17', '18', '19', '20',
   '21', '22', '23', '24', '25', '26', '27', '28', '29', '30',
    '32', '33', '34'].freeze

  MODELS = ['SSE-SJB4', 'SSE-SAW5', 'SSE-SCG6', 'SSE-SCT9', 'SSE-SDF8', 'SSE-SCV2', 'SSE-SDS5', 'SSE-SFW9',
    'SSE-SGM1', 'SSE-SJJ6', 'SSE-SJJ8', 'SSE-SKG5', 'SSE-SLB2', 'SSE-SLB7', 'SSE-SKP7', 'SSE-SKP2',
    'SSE-JJ7', 'SSE-SJA4', 'SSE-SJZ3', 'SSE-SKK6', 'SSE-SJJ6', 'SSE-SKG5', 'SSE-SHQ2', 'SSE-SLW6', 'SSE-SLW7', 'MIX-SGK6',
    'MIX-SJZ5', 'MIX-SHR5', 'MIX-SKS1', 'MIX-SLJ9', 'BBK-SJV5', 'BBK-SKC1', 'BBK-SJQ5', 'BBK-SDH6', 'BBK-SJQ6', 'BBK-SJV6',
    'BBK-SHX4', 'BBK-SHV2', 'BBK-SHD2', 'BBK-SFC8', 'BBK-SLF7', 'BBK-SLG8', 'BBK-SLG9', 'BBK-SLF7', 'BBK-SLW1',
    'OPO-SCP5', 'OPO-SCR2', 'OPO-SDY7', 'OPO-SACJ1', 'OPO-SGL3', 'OPO-SHC9', 'OPO-SHX3', 'OPO-SHN6', 'OPO-SHS8',
    'OPO-SHV3', 'OPO-SKM1', 'OPO-SKY1', 'OPO-SJB4', 'OPO-SEC3', 'OPO-SHC9', 'OPO-SDY5', 'OPO-SKY1', 'OPO-SLE2', 'OPO-SLV9', 'OPO-SLX7', 'OPO-SLE3',
    'TSNSBC4', 'TSNSJY4', 'TSN-SKA6', 'MTO-SDJ4', 'MTO-SCR6', 'MTO-SDR3', 'MTO-SBW3', 'MTO-SHV1', 'MTO-JU8', 'MTO-SJB1'].freeze

  private

  def set_default_date_and_time
    self.date = created_at.strftime('%Y-%m-%d')
    self.time ||= created_at.in_time_zone('Asia/Kolkata').strftime('%H:%M:%S')
  end

  def validate_qty_limit
    if qty.present? && qty.to_i > 25
      errors.add(:qty, "cannot exceed 25 parts")
    end
  end
end

app/controllers/fas_controller.rb
require 'axlsx'

class FasController < ApplicationController
	before_action :authenticate, only: :search

  def index
  	@fas = Fa.paginate(page: params[:page], per_page: 8)
  end

  def show
  	@fa = Fa.find(params[:id])
  end

  def new
  	@fa = Fa.new
  end

  def create
  	@fa = Fa.new(fa_params)
    if @fa.save
      redirect_to @fa, notice: 'Data was successfully saved.'
    else
      flash.now[:alert] = 'Data is not complete or correct.'
      render "new"
    end
  end

  def export_excel
	  # Find the Fa object using params[:id]
	  @fa = Fa.find(params[:id])
	  respond_to do |format|
	    format.xlsx {
	      # Now that @fa is assigned, you can access its barcodes
	      @barcode = @fa.barcodes
	      # Proceed with building and rendering the Excel file
	      render xlsx: 'export_excel', filename: "fas_data_#{Time.now.strftime('%Y%m%d%H%M%S')}.xlsx"
	    }
	  end
	end

	def export_to_excel
	 	@submitted_fas = Fa.includes(:barcodes).all # Replace with your logic to retrieve data
    respond_to do |format|
      format.xlsx {
        # Create an Axlsx::Package and workbook
        xlsx_package = Axlsx::Package.new
        wb = xlsx_package.workbook

        # Define a centered and bordered style for the entire worksheet
        centered_bordered_style = wb.styles.add_style(
          alignment: { horizontal: :center },
          border: { style: :thin, color: '000000' } # Black border lines
        )

        # Define a bold style for the header
        bold_style = wb.styles.add_style(b: true, alignment: { horizontal: :center }, border: { style: :thin, color: '000000' })

         # Define a red style for the "NG" status
        red_style = wb.styles.add_style(
          b: true,
          alignment: { horizontal: :center },
          border: { style: :thin, color: '000000' },
          fg_color: 'FF0000' # Red background color
        )
         # Define a new style with an increased font size for the title row
  			title_style = wb.styles.add_style(b: true, sz: 14, alignment: { horizontal: :center },
  			 border: { style: :thin, color: '000000' })

        	
        # Add worksheet and headers
        wb.add_worksheet(name: 'Failure Analysis Data') do |sheet|
          # Add bold, centered, and bordered header row
          sheet.add_row ['Failure Analysis Data'], style: title_style
          sheet.merge_cells("A1:K1") # Merge cells for the title row
          sheet.add_row ['Sr No.', 'Date', 'Time', 'Line', 'Model', 'Barcode', 'Out Date', 'Out Time', 'FT Status', 'Remarks', 'Time Gap'], style: bold_style

          # Add data rows with the same style
          serial_number = 0
          @submitted_fas.reverse_each.with_index(1) do |fa, index|
            fa.barcodes.each do |barcode|
              serial_number += 1
              # Check if the status is "NG" and apply red_style
              status_style = (barcode.status == 'NG' ? red_style : centered_bordered_style)
              sheet.add_row [
                serial_number,
                fa.date&.strftime('%Y-%m-%d'),
                fa.time&.strftime('%H:%M:%S'),
                fa.Line,
                fa.Model,
                barcode.value,
                (barcode.status.present? ? barcode.updated_at&.strftime('%Y-%m-%d') : ''),
                (barcode.status.present? ? barcode.updated_at&.strftime('%H:%M:%S') : ''),
                barcode.status,
                barcode.remarks,
                (barcode.updated_at.present? && fa.time.present? && barcode.status.present? ? Time.at((barcode.updated_at.to_time - fa.time.to_time).abs).utc.strftime('%H:%M:%S') : '')
              ], style: status_style
            end
          end
        end

        # Send the file to the user
        send_data xlsx_package.to_stream.read, filename: "AF_data_#{Time.now.strftime('%Y%m%d%H%M%S')}.xlsx", type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', disposition: 'attachment'
      }
    end
  end

  def destroy
	  @fa = Fa.find(params[:id])
	  @fa.destroy
	  redirect_to @fa, notice: 'Data was successfully destroyed.'
	end

  def submit_barcode_data
	  @fa = Fa.find(params[:format])
	  barcode_values = params[:fa][:barcodes].map { |barcode| barcode[:value] }
	  if barcode_values.uniq.length != barcode_values.length
		  flash.now[:alert] = 'Do not enter duplicate Barcodes.'
		elsif all_values_present = barcode_values.all?(&:present?)
		  if all_values_present
		    # Build Barcode objects associated with @fa
		    barcode_values.each do |value|
		      @fa.barcodes.build(value: value)
		    end

		    # Save the @fa instance and all associated Barcode objects to the database
		    if @fa.save
		    	flash[:notice] = 'Barcode data submitted successfully.'
		    	# render 'submitted_data'
		      redirect_to  submitted_data_fa_path(@fa), notice: 'Barcode data submitted successfully.'
		      # redirect_to barcodes_fa_path(@fa), notice: 'Barcode data submitted successfully.'
		    else
		      flash.now[:alert] = 'Failed to save barcode data.'
		      render 'show'
		    end
		  end
		end
	end

	def barcodes
	  @fa = Fa.find(params[:id])
	  @barcodes = @fa.barcodes
	end

	def submitted_data
    @submitted_fas = Fa.includes(:barcodes).all
  end

  def search
		password = params[:password]
	  @barcodes = Barcode.where(value: params[:barcode])
	  if @barcodes.present?
	  	# @search = @barcodes.first.fa
	    @search = @barcodes.map(&:fa)
	  else
	    flash.now[:alert] = "No matching barcodes found."
	    @search = []
	  end
	end

	def update_status_and_remarks
	  barcode = params[:barcode]
	  status = params[:status]
	  remarks = params[:remarks]

  	barcode_record = Barcode.where(value: barcode, status: nil)
	  if barcode_record
	  	# Check if the status and remarks are present and not empty
	  	# barcode_record.update(status: status.presence || barcode_record.status, remarks: remarks.presence || barcode_record.remarks)
	    barcode_record.update(status: status, remarks: remarks)
	    # updated_at_time = barcode_record.updated_at
	    flash.now[:alert] = 'Status and remarks updated successfully.'
	  else
	    flash.now[:alert] = 'Barcode not found.'
	    barcode_record = []
	  end
	  # render 'search'
	  redirect_to search_fas_path(barcode: '')
	end

	def graphs
		month_data = Fa.group("strftime('%Y-%m', created_at)").sum(:qty)
		@monthly_data = month_data.transform_keys! { |key| Date.parse(key + '-01').strftime('%b') }
		@ng_data = Barcode.where(status: "NG").group("strftime('%d-%m', created_at)").count
		@barcode_data = Barcode.group("strftime('%d-%m', created_at)").count
		@merged_data = @barcode_data.merge(@ng_data) { |key, ok_count, ng_count| [ok_count, ng_count] }
		@fa_data = Fa.includes(:barcodes).all.pluck("Model","Line")
	end

	def destroy_old
	  Fa.older_than_two_months.destroy_all
	  respond_to do |format|
	    format.html { redirect_to fas_url, notice: 'Old records were successfully deleted.' }
	    format.json { head :no_content }
	  end
	end


private

  def fa_params
    params.require(:fa).permit(:Line, :Model, :qty)
  end

  def authenticate
	  # Replace 'your_password' with your actual password
	  correct_password = '9023579'

	  # Check if the user is not already authenticated in the current session
	  unless session[:authenticated]
	    # If the current action is 'search', allow access without password check
	    return if params[:action] == 'search' && !params[:barcode].nil?

	    if params[:password] == correct_password
	      session[:authenticated] = true
	    else
	      flash[:alert] = 'Incorrect password. Access denied.'
	      redirect_to new_fa_path
	    end
	  else
	    # If the flag is already set (user is authenticated),
	    # reset the flag when the search button is clicked
	    session[:authenticated] = false
	  end
	end
end

app/helpers/fas_helper.rb
module FasHelper
end

app/views/fas/_fa.html.erb
<h1>FA Partial</h1>

app/views/fas/barcodes.html.erb
<div class="container">
  <h2 class="basic-head fw-bold text-center bg-primary p-3 my-3">Barcode Data</h2>
  <div class="d-flex align-items-center justify-content-between mb-3">
    <%= link_to "Home", new_fa_path, class: 'btn btn-primary' %>
    <%= link_to 'Export to Excel', export_excel_fas_path(id: @fa.id, format: 'xlsx'), class: 'btn btn-success' %>
  </div>
  <table class="table table-striped table-bordered align-middle text-center">
    <tbody>
      <tr>
        <th style="width: 80px">Sr No.</th>
        <th>Date</th>
        <th>Time</th>
        <th>Line</th>
        <th>Model</th>
        <th>Barcode</th>
      </tr>
      <% @fa.barcodes.each_with_index do |barcode, index| %>
        <tr>
          <td><%= index + 1 %></td>
          <td><%= @fa.date&.strftime('%Y-%m-%d') %></td>
          <td><%= @fa.time&.strftime('%H:%M:%S') %></td>
          <td><%= barcode.fa.Line %></td>
          <td><%= barcode.fa.Model %></td>
          <td><%= barcode.value %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/fas/index.html.erb
<div class="container">
  <h2 class="basic-head fw-bold text-center bg-primary p-3 my-3">FA DATA LIST</h2>
  <table class="table table-striped table-bordered align-middle text-center">
    <tbody>
      <tr>
        <th style="width: 80px">Sr No.</th>
        <th>Date</th>
	      <th>Time</th>
	      <th>Line</th>
	      <th>Model</th>
	      <th>Qty</th>
	      <th>Actions</th>	
      </tr>
      <% @fas.each_with_index do |fa, index| %>
	      <tr>
	        <td><%= index + 1 %></td>
	        <td><%= fa.date&.strftime('%Y-%m-%d') %></td>
	        <td><%= fa.time&.strftime('%H:%M:%S') %></td>
	        <td><%= fa.Line %></td>
	        <td><%= fa.Model %></td>
	        <td><%= fa.qty %></td>
	        <td>
	        	<div class="d-flex justify-content-center">
		        	<%#= link_to "Show", fa_path(fa) %>
		        	<%#= button_to "Delete", fa, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger mx-2" %>
		        	<%= link_to 'View Barcodes', barcodes_fa_path(fa), class: "btn btn-primary mx-2" %></td>
		        </div>
	      </tr>
	    <% end %>
    </tbody>
  </table>
	<div class="pagination my-3 d-flex justify-content-center">
	  <%= will_paginate @fas %>
	</div>
</div>

app/views/fas/new.html.erb
<div class="back-bg d-flex align-items-center justify-content-center">
  <div class="login-inner">
    <h2 class="fw-bold text-center border-bottom pb-3 mb-3">FA Data Entry</h2>
    <%= form_with(model: @fa) do |form| %>
      <div class="mb-2">
        <% if flash.now[:alert] %>
          <div class="alert alert-danger d-flex align-items-center" role="alert">
            <%= flash.now[:alert] %>
          </div>
        <% end %>
      </div>
      <div class="mb-2">
        <%= form.label :Line, class: 'form-label' %>
        <%= form.collection_select(:Line, Fa::LINES, :to_s, :humanize, { prompt: 'Select Line' }, class: 'form-control') %>
      </div>
      <div class="mb-2">
        <%= form.label :Model, class: 'form-label' %>
        <%= form.collection_select(:Model, Fa::MODELS, :to_s, :upcase, { prompt: 'Select Model' }, class: 'form-control') %>
      </div>
      <div class="mb-2">
        <%= form.label :qty, class: 'form-label' %>
        <%= form.text_field :qty, class: 'form-control', pattern: '\d+', placeholder: 'Enter quantity (Max: 25)', autocomplete: 'off' %>
      </div>
      <%= form.submit 'Submit', class: 'btn btn-primary w-100' %>
    <% end %>
  </div>
</div>

app/views/fas/search.html.erb
<!-- app/views/fas/search.html.erb -->
<div class="container mt-4">
  <h2 class="basic-head fw-bold text-center bg-primary p-3 my-3">Search Barcode</h2>
  <%= form_with(url: search_fas_path, method: :get, local: true, class: "form-inline justify-content-center mb-3") do %>
    <div class="form-group">
      <%= text_field_tag :barcode, params[:barcode], class: "form-control mr-2 my-2", placeholder: "Enter Barcode", autocomplete: 'off' %>
    </div>
    <div class="text-center">
      <%= submit_tag "Search", class: "btn btn-primary my-2" %>
    </div>
  <% end %>

  <% if @search.present? %>
    <h2 class="basic-head fw-bold text-center bg-primary p-3 my-3">Search Result</h2>
    <table class="table table-striped table-bordered align-middle text-center">
      <thead>
        <tr>
          <th style="width: 80px">Sr No.</th>
          <th>Date</th>
          <th>Time</th>
          <th>Line</th>
          <th>Model</th>
          <th>Barcode</th>
          <th>Analysis</th>
        </tr>
      </thead>
      <tbody>
			  <% @search.each_with_index do |fa, index| %>
			    <tr>
			      <td><%= index + 1 %></td>
			      <td><%= fa.date&.strftime('%Y-%m-%d') %></td>
			      <td><%= fa.time&.strftime('%H:%M:%S') %></td>
			      <td><%= fa.Line %></td>
			      <td><%= fa.Model %></td>
			      <% fa.barcodes.each do |barcode| %>
			        <% if barcode.value == params[:barcode] %>
			          <td>
			          	<%= barcode.value %>
			            <!-- Add a hidden field for status -->
			            <input type="hidden" class="status-field" data-barcode="<%= barcode.value %>" value="<%= barcode.status %>">
			            <!-- Add a hidden field for remarks -->
			            <input type="hidden" class="remarks-field" data-barcode="<%= barcode.value %>" value="<%= barcode.remarks %>">
			          </td>
			          <% if barcode.status.present? && barcode.remarks.present? %>
			          	<td>
						        <%= barcode.status %>
						      </td>
						      <td>
						        <%= barcode.remarks %>
						      </td>
						      <td>
						      </td>
						    <% else %>  
				          <td>
									  <!-- Add form fields for Status and Remarks -->
									  <%= form_tag(update_status_and_remarks_fas_path, method: :post, id: "update_form_#{barcode.value}") do %>
									    <%= hidden_field_tag :barcode, barcode.value %>
									    <!-- Column for Status -->
									    <div class="form-group">
									      <label for="status">Status</label>
									      <%= text_field_tag :status, barcode.status, class: 'form-control', placeholder: 'Update Status', value: 'OK' %>
									    </div>
									  </td>
									  <td>
									    <!-- Column for Remarks -->
									    <div class="form-group">
									      <label for="remarks">Remarks</label>
									      <%= text_field_tag :remarks, barcode.remarks, class: 'form-control', placeholder: 'Update Remarks', value: 'N/A', autocomplete: 'off' %>
									    </div>
									  </td>
									  <td>
									    <%= submit_tag 'Update', class: 'btn btn-primary btn-sm mt-1', form: "update_form_#{barcode.value}" %>
									  </td>
									  <% end %>
									</td>
								<% end %>	
			        <% end %>
			      <% end %>
			    </tr>
			  <% end %>
			</tbody>
    </table>
  <% elsif flash[:alert] %>
    <div class="alert alert-info text-center mt-3" role="alert">
      <%= flash[:alert] %>
    </div>
  <% end %>
</div>

app/views/fas/submitted_data.html.erb
<div class="container">
  <div class="row">
    <div class="col-2 filter-column mt-2">
      <div class="form-group mb-2">
        <div class="col-md-11">
          <label for="filterDateFrom">From Date:</label>
          <input type="date" id="filterDateFrom" class="form-control">
        </div>
        <div class="col-md-11">
          <label for="filterDateTo">To Date:</label>
          <input type="date" id="filterDateTo" class="form-control">
        </div>
        <div class="col-md-11">
          <label for="filterTimeFrom">From Time:</label>
          <input type="time" id="filterTimeFrom" class="form-control">
        </div>
        <div class="col-md-11">
          <label for="filterTimeTo">To Time:</label>
          <input type="time" id="filterTimeTo" class="form-control">
        </div>
        <div class="row">
          <div class="col-md-6 my-2">
            <button id="filterBtn" class="btn btn-primary custom-btn" style="background: url('/filter-solid.svg') no-repeat, #198754; background-size: 20px 20px; background-position: 5px center; padding-left: 30px;">Filter</button>
          </div>
          <div class="col-md-6 my-2">
            <button id="resetBtn" class="btn btn-secondary">Reset</button>
          </div>
        </div>
      </div>
      <div class="d-flex align-items-center justify-content-between mb-3">
        <%= link_to export_to_excel_fas_path(format: 'xlsx'), class: 'btn btn-success popover-dismiss', tabindex: '0', role: 'button', data: { bs_toggle: 'popover', bs_content: "Entire data is downloaded in Excel file.", bs_title: 'Hi', bs_trigger: 'focus' } do %>
          <img src="/download.svg" alt="Download" style="height: 20px;width: 20px;">
          Export to Excel
        <% end %>
      </div>
        <%= button_to 'Delete Old Records', destroy_old_fas_path, method: :delete, data: { confirm: 'Are you sure you want to delete records older than two months?' }, class: 'btn btn-danger' %>
    </div>
    <div class="col-10">
      <nav class="navbar navbar-dark bg-primary p-2 my-2 rounded">
        <div class="container-fluid">
          <a class="navbar-brand fw-bold d-block mx-auto" style="width: max-content; font-size: 28px;">Failure Analysis Data</a>
          <form class="d-flex">
            <div class="input-group">
              <div style="position: relative;">
                <input id="barcodeSearchInput" class="form-control me-2" type="search" placeholder="Search Barcode" aria-label="Search" autocomplete="off" style="padding-right: 30px;">
                <div style="position: absolute; top: 50%; transform: translateY(-50%); right: 10px;">
                  <img src="/magnifying-glass-solid.svg" alt="Search" style="height: 20px; width: 20px;">
                </div>
              </div>
              <div class="input-group-append">
                <button id="barcodeSearchBtn" class="btn btn-success" type="button" style="border-color: #e7e7;">Search</button>
              </div>
            </div>
          </form>
        </div>
      </nav>
      <div class="table-container">
        <table class="table table-striped table-bordered align-middle text-center">
            <tbody>
              <tr>
                <th>Sr No.</th>
                <th>Date</th>
                <th>Time</th>
                <th>Line</th>
                <th style="width: 100px">Model</th>
                <th style="width: 330px">Barcode</th>
                <th style="width: 130px">Out Date</th>
                <th>Out Time</th>
                <th style="width: 100px">FT Status</th>
                <th>Remarks</th>
                <th>Time Gap</th>
              </tr>
              <% serial_number = 0 %>
              <% @submitted_fas.reverse_each.with_index(1) do |fa, index| %>
                <% fa.barcodes.each do |barcode| %>
                  <% serial_number += 1 %>
                  <tr class="table-row">
                    <td><%= serial_number %></td>
                    <td><%= fa.date&.strftime('%Y-%m-%d') %></td>
                    <td><%= fa.time&.strftime('%H:%M:%S') %></td>
                    <td><%= fa.Line %></td>
                    <td><%= fa.Model %></td>
                    <td><%= barcode.value %></td>
                    <td>
                      <% if barcode.status.present? %>
                        <%= barcode.updated_at&.strftime('%Y-%m-%d') %>
                      <% else %>
                        <%= '' %>
                      <% end %>
                    </td>
                    <td>
                      <% if barcode.status.present? %>
                        <%= barcode.updated_at&.strftime('%H:%M:%S') %>
                      <% else %>
                        <%= '' %>
                      <% end %>
                    </td>
                    <td class="<%= 'text-danger' if barcode.status == 'NG' %>"><%= barcode.status %></td>
                    <td><%= barcode.remarks %></td>
                    <td>
                      <% if barcode.updated_at.present? && fa.time.present? && barcode.status.present? %>
                        <!-- dont delete below line: these lines show date gap along with time within row.-->
                        <%# updated_at_time = barcode.updated_at %>
                        <%# fa_time = fa.time %>
                        <%#= Time.at(time_difference).utc.strftime('%d days %H:%M:%S') %>
                        <% updated_at_time = barcode.updated_at.to_time %>
                        <% fa_time = fa.time.to_time %>
                        <% time_difference = (updated_at_time - fa_time).abs %>
                        <%= Time.at(time_difference).utc.strftime('%H:%M:%S') %>
                      <% else %>
                        <%= '' %>
                      <% end %>
                    </td>
                  </tr>
                <% end %>
              <% end %>
            </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

<script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>

<style type="text/css">
  .container {
    max-width: 1600px;
  }
  .mb-2 {
    margin-top: 6.5rem!important;
  }
  .col-2 {
    width: 15%;
  }
  .filter-column {
    background-color: #0d6efd;
    border-radius: 10px;
  }
  .custom-btn {
    background-color: #e7e7;
  }
  .table-container {
    max-height: 635px; /* Adjust the maximum height as needed */
    overflow-y: auto; /* Add a vertical scrollbar when the content overflows */
  }
</style>

<script>
  $(document).ready(function() {
    var initialVisibleRows = $(".table-row").toArray(); // Array to store initially visible rows

    $("#filterBtn, #barcodeSearchBtn").on("click", function() {
      const fromDate = new Date($("#filterDateFrom").val());
      const toDate = new Date($("#filterDateTo").val());
      const fromTime = $("#filterTimeFrom").val();
      const toTime = $("#filterTimeTo").val();
      const searchText = $("#barcodeSearchInput").val().trim().toLowerCase();

      $(".table-row").each(function() {
        const rowDate = new Date($(this).find("td:eq(1)").text());
        const rowTime = $(this).find("td:eq(2)").text(); // Assuming time is in the third cell
        const barcodeText = $(this).find("td:eq(5)").text().trim().toLowerCase(); // Assuming barcode is in the sixth cell

        const isValidDate = !isNaN(fromDate) && !isNaN(toDate) && !isNaN(rowDate) ? (rowDate >= fromDate && rowDate <= toDate) : true;
        const isValidTime = (!fromTime || rowTime >= fromTime) && (!toTime || rowTime <= toTime);
        const isValidBarcode = searchText === "" || barcodeText.includes(searchText);

        if (isValidDate && isValidTime && isValidBarcode) {
          $(this).show();
        } else {
          $(this).hide();
        }
      });
    });

    $("#resetBtn").on("click", function() {
      // Show initially visible rows
      $(initialVisibleRows).show();
      // Clear input fields
      $("#filterDateFrom, #filterDateTo, #filterTimeFrom, #filterTimeTo, #barcodeSearchBtn").val("");  
    });
  });
</script>

<script>
    // Initialize popover for the export link
    var popover = new bootstrap.Popover(document.querySelector('.popover-dismiss'), {
      trigger: 'focus'
    });
</script>